### ISSUE TITLE
Game freezes after player time runs out -- Critical

### ISSUE THREAD

**Issue by malikh22** [lpszeto/BoggleGame#1]
Component: GUI, likely Game State as well

Problem: The game freezes when the player's time runs out. The bar at the top correctly turns red to indicate that the player is out of time, and the player is correctly unable to send further actions. However, the AI does not make a move. This is a critical issue as the game is no longer able to progress past the player's first turn. A potential cause is the calcutation of time-- in this state, the time reads 0:0-1. 

Steps to recreate: 
1- Start a new game with the dumb AI
2- Play until the timer runs out
3- Attempt to add additional words (which doesn't do anything)
4- The AI will not make a turn, and the game is effectively frozen.

**Comment by Gmunster33** [comment]
A menu now pops up prompting you to restart the game. Enjoy!

**Comment by malikh22** [comment]
Fixed--the game ends when the time runs out.
