### ISSUE TITLE
Selecting 2 Human Players Causes Game to Crash

### ISSUE THREAD

**Issue by zmader** [lpszeto/BoggleGame#10]
Minor Bug - When choosing what kind of player one wants to play against, if “Human Player” is chosen then the game crashes 
Component - Other (Main Activity) 
	Having the option of selecting a Human Player as an opponent implies one could play with another human on the same tablet. Most games have this same option, yet the game does not crash.

**Comment by Gmunster33** [comment]
Game framework now warns you and prevents you from doing this.

**Comment by mohammap22** [comment]
Bug has been fixed.

**Comment by MwKau** [comment]
Coolio, the game framework still takes a while to respond, but it doesn't crash
