### ISSUE TITLE
Human at player 2 causes issues.

### ISSUE THREAD

**Issue by VandanBh** [lpszeto/BoggleGame#11]
Description: When the human becomes player two and the AI is left with player one, the word bank of the green box is shown, but this word bank is not the human player's, it is the AI's word bank. This word bank stays there the entire time and makes it very easy for the user to just cheat and use those words. The human player also takes the red color, and the word bank for this one doesn't work when words are typed in. The colors are also not coordinated, so that makes it a bit confusing. 

Severity: Major
Component: GUI / Game Rules

Reproduce: Open the game, make the first player an AI (either dumb or smart), then make the second player the Human Player, start the game, the word bank will appear on the right side of the screen in the green box filled with all the words the AI has already gotten. When you type a word it is in green, and the red points increase accordingly, but don't go to the word bank of the red box.

**Comment by Gmunster33** [comment]
The AI's word bank no longer appears. The GUI player's words will also appear instead in red, both in the word bank and in the window below the board. Good comment!

**Comment by VandanBh** [comment]
Yup, looks fixed!
