### ISSUE TITLE
Setting both players to Human causes crash

### ISSUE THREAD

**Issue by MwKau** [lpszeto/BoggleGame#13]
When attempting to select both players as the human player 1, the game crashes upon leaving the starting GUI

Severity: Major
Component: Other

When a second human player is selected, so that both player slots read "Local Human Player 1", the game crashes while transitioning to the next room after a couple of seconds of loading.

To recreate this bug, the user must click on the drop down menu that selects "player type" for the computer player. Then, after choosing "Local Human Player 1" and pressing the [START GAME] button, the game hangs for around 3 seconds before crashing.

**Comment by Gmunster33** [comment]
The game framework now catches this and throws an error when two GUI players are selected.

**Comment by RJMNillo** [comment]
On my end it does not crash, but it just does not respond
