### ISSUE TITLE
Can get words to show up at bottom of screen when timer runs out.

### ISSUE THREAD

**Issue by braedenlane** [lpszeto/BoggleGame#14]
When the timer runs out, interaction with the letters seems to not be possible, but if you do lots of quick inputs, letters show up.

Severity: Minor (Couldn't get them to add to the word bank)
Component: Game Rules

When the timer runs out, I should not be able to interact with the GUI letters at all. But by doing the following, I can get the GUI to show me the letters I am interacting with, which could, with more experimentation, lead to cheating during the game in allowing more time for players to find words after the timer is up.

To recreate:
Let a game run to zero on the time.
Tap a few letters that would've worked before (three that are all adjacent and are legal suggestions).
Use four fingers and quickly hit lots of other letters.
Notice how words reappear at the bottom when they would not before.

**Comment by Gmunster33** [comment]
After the game is over, the user may now select letters and have a word show up at the bottom of the screen. However, the user cannot submit this word for score.

**Comment by braedenlane** [comment]
This does seem like an okay fix to this problem. As long as you cannot change the results of the game, and since it does not allow the player to cheat, it seems to be a good solution. There solution also is present in the implementation.
