### ISSUE TITLE
When timer runs out, no end of game trigger has not been called.

### ISSUE THREAD

**Issue by RJMNillo** [lpszeto/BoggleGame#15]
Component: Game Rules
Severity: Major

The requirement that prompts players to play again is still not implemented, as the end of game trigger does not go off when the timer runs out.

Reproduction:
Play the game until the time runs out, and you will see that the game does not do anything else.

**Comment by Gmunster33** [comment]
A menu from the game framework now pops up prompting the user to play again or quit!

**Comment by RJMNillo** [comment]
Works, can see winner, word banks, and prompt to play again.
