### ISSUE TITLE
Can’t see words when DumbAI is player1 -- Major

### ISSUE THREAD

**Issue by faker20** [lpszeto/BoggleGame#16]
Component: GUI
Problem: The game will not show found words when DumbAI is player0. I made the gamescore 3 but can’t see the words I guessed correctly. This is a major error because it makes the user think they aren’t playing.
Steps to recreate:
1-Start a new game with the dumbAI as player0
2-Guess a few correct words

**Comment by Gmunster33** [comment]
Fixed! The player's words now show up.

**Comment by hendersj22** [comment]
FIxed
