### ISSUE TITLE
No Rules Visible

### ISSUE THREAD

**Issue by hendersj22** [lpszeto/BoggleGame#2]
For an unknown player it is hard to know what to do.

This is a major issue. 

Essentially in this situation you cannot figure out what to do if you haven't played before. 

In order to reproduce this issue you start the game and then observe that there is no rules option.

**Comment by Gmunster33** [comment]
The team sent Dr. Vegdahl an updated user manual which should be available to supplement the game. Although not built into the game, the community should now have access to the game rules and instructions!

**Comment by hendersj22** [comment]
Great, I found your user manual and was able to access it. Fixed
