### ISSUE TITLE
Some letters won't press- critical -- GUI 

### ISSUE THREAD

**Issue by hendersj22** [lpszeto/BoggleGame#4]
When I try to press certain letters the game doesn't respond. 

This is a critical failure in the GUI

When I try to press a 3rd or 4th letter it won't respond. This happens when I try to spell a longer word or when I try to just type a letter sometimes they stop responding. I'm not sure exactly what the issue is. 

To reproduce this issue I would say you can try typing a word over 3 letters and see if it stops responding. Also, try deleting a letter and putting it back.

**Comment by Gmunster33** [comment]
The team could not reproduced this issue; we could make a word the size of the entire board without issue, as well as use the delete key and put letters back afterwards. The latest update to the GUI also includes changing the color of the letters that the player has selected for easier tracking. Consider trying again, and letting us know if the issue persists.

**Comment by malikh22** [comment]
Fixed-- all letters can be selected

**Comment by hendersj22** [comment]
Fixed
