### ISSUE TITLE
Possible to select invalid character inputs

### ISSUE THREAD

**Issue by zmader** [lpszeto/BoggleGame#5]
Bug- invalid combinations (selecting letters that are not next to each other)
	Minor bug- doesn’t occur very often / consistently
Component - game rules
	I hit the screen randomly with my hand, and it gave a combination of letters that shouldn’t be able to be selected. This bug cannot be intentionally recreated, because there is a lot of randomness that goes into creating the bug

**Comment by Gmunster33** [comment]
The team could not replicate. The team also pushed an update to the GUI that makes it substantially faster/more responsive, so this likely solved the issue

**Comment by zmader** [comment]
Seems to be fixed, I haven't been able to replicate this either.
