### ISSUE TITLE
Swapping Positions of Human and AI Player Causing Multiple Issues with GUI

### ISSUE THREAD

**Issue by zmader** [lpszeto/BoggleGame#7]
Bug - Having the human player as second player and AI as first player causes the word bank not to update properly.
Major Bug - Game does not function properly if played in this way.
Component - GUI
	To replicate this bug, switch the order of the AI and human players before starting the game. This causes the score to update for the red player when the human player gets a word, and the word list does not update. From what I’ve noticed, the AI player does not score any points when the game plays like this. This bug makes it hard to play properly because you cannot see what words you have already selected, making the game harder than intended. It also makes the game effectively a single player game, because the AI does not do anything.

**Comment by Gmunster33** [comment]
Fixed!

**Comment by mohammap22** [comment]
Bug has been fixed.
