### ISSUE TITLE
GUI not responding after timer completes

### ISSUE THREAD

**Issue by zmader** [lpszeto/BoggleGame#8]
Minor Bug - After the timer reaches zero, the “Games Won” counter does not change and nothing can be done to quit or continue the game. 
Component - Game Rules 
Yet, it is still possible to submit letters. This bug can be intentionally recreated by waiting out the timer while playing. It seems that their onFinish method is not updating the game properly. And there is no method to compare the player and AI scores.

**Comment by Gmunster33** [comment]
End of game menu now pops up and displays scores and a winner. The team decided that tracking games won will not be tracked, since it is not a traditional component of Boggle.

**Comment by mohammap22** [comment]
Issue is fixed, player is shown who won and has the option to play again.
